-- This file is automatically generated by Themery.
-- It contains the currently selected theme.
-- Do not edit this file manually.

vim.g.catppuccin_flavour = "macchiato"
vim.cmd.colorscheme("catppuccin")
